name: Docker Build/Publish Image
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7,linux/amd64
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_image::$DOCKER_REGISTRY/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
    - name: Docker Login
      if: success()
      run: |
        echo "${DOCKER_PASSWORD}" | docker login $DOCKER_REGISTRY --username "$GITHUB_REPOSITORY_OWNER" --password-stdin
    - name: Run Buildx (push image)
      if: success()
      run: |
        docker buildx build --platform ${DOCKER_TARGET_PLATFORM} --tag ${{ steps.prepare.outputs.docker_image }} --output type=image,push=true .
